### ISSUE TITLE
数据量大anr

### ISSUE THREAD

**Issue by ChloeDimen** [zhushenwudi/SerialPortHelper#1]
数据量大会anr。设置最大接收数据10248，如果接收的没有到最大的长度，不会返回onReceiveData

**Comment by zhushenwudi** [comment]
> 数据量大会anr。设置最大接收数据10248，如果接收的没有到最大的长度，不会返回onReceiveData

这个问题我会看一下，项目很久没更新了，之后的问题会同步更新到 Kt项目上。还有就是，数据长度建议最大为256（0XFF）

**Comment by zhushenwudi** [comment]
> 数据量大会anr。设置最大接收数据10248，如果接收的没有到最大的长度，不会返回onReceiveData

今天更新了我最近在用的库，文档也出了。可以参考一下，这边两个库已经不建议使用了
https://github.com/zhushenwudi/serialport
